INSERT INTO Coaches(COACH_ID, COACH_NAME, COACH_SALARY) VALUES(1, 'C1', 1999);
INSERT INTO Coaches(COACH_ID, COACH_NAME, COACH_SALARY) VALUES(2, 'C2', 2999);
INSERT INTO Coaches(COACH_ID, COACH_NAME, COACH_SALARY) VALUES(3, 'C3', 3999);

INSERT INTO Doctors(DOCTOR_ID, DOCTOR_NAME, DOCTOR_SALARY) VALUES(1, 'D1', 199);
INSERT INTO Doctors(DOCTOR_ID, DOCTOR_NAME, DOCTOR_SALARY) VALUES(2, 'D2', 299);
INSERT INTO Doctors(DOCTOR_ID, DOCTOR_NAME, DOCTOR_SALARY) VALUES(3, 'D3', 399);

INSERT INTO Sponsors(SPONSOR_ID, SPONSOR_NAME, SPONSOR_NETWORTH) VALUES(1, 'S1', 100000);
INSERT INTO Sponsors(SPONSOR_ID, SPONSOR_NAME, SPONSOR_NETWORTH) VALUES(2, 'S2', 200000);
INSERT INTO Sponsors(SPONSOR_ID, SPONSOR_NAME, SPONSOR_NETWORTH) VALUES(3, 'S3', 300000);

INSERT INTO Announcers(ANNOUNCER_ID, ANNOUNCER_NAME, ANNOUNCER_SALARY) VALUES(1, 'A1', 10);
INSERT INTO Announcers(ANNOUNCER_ID, ANNOUNCER_NAME, ANNOUNCER_SALARY) VALUES(2, 'A2', 20);
INSERT INTO Announcers(ANNOUNCER_ID, ANNOUNCER_NAME, ANNOUNCER_SALARY) VALUES(3, 'A3', 30);


INSERT INTO Companies(COMPANY_ID, COMPANY_NAME) VALUES(1, 'UFC', 199);
INSERT INTO Companies(COMPANY_ID, COMPANY_NAME) VALUES(2, 'PFL', 299);
INSERT INTO Companies(COMPANY_ID, COMPANY_NAME) VALUES(3, 'ONE', 399);

INSERT INTO Fighters(FIGHTER_ID, FIGHTER_NAME, FIGHTER_SALARY, FIGHTER_WEIGHT) VALUES(1, 'GSP', 10, 77);
INSERT INTO Fighters(FIGHTER_ID, FIGHTER_NAME, FIGHTER_SALARY, FIGHTER_WEIGHT) VALUES(2, 'Connor', 12, 77);
INSERT INTO Fighters(FIGHTER_ID, FIGHTER_NAME, FIGHTER_SALARY, FIGHTER_WEIGHT) VALUES(3, 'Jones', 13, 120);

INSERT INTO Fans(FAN_ID, FAN_NAME) VALUES(1, 'F1');
INSERT INTO Fans(FAN_ID, FAN_NAME) VALUES(2, 'F2');
INSERT INTO Fans(FAN_ID, FAN_NAME) VALUES(3, 'F3');


SELECT * FROM Coaches
SELECT * FROM Doctors
SELECT * FROM Announcers
SELECT * FROM Sponsors
SELECT * FROM Fans
SELECT * FROM Fighters
SELECT * FROM Companies


