USE [ERIK MAIDIK MMA]
GO
	
	DROP TABLE Treats
	DROP TABLE Supports
	DROP TABLE Works_for
	DROP TABLE Fighters
	DROP TABLE Companies
	DROP TABLE Doctors
	DROP TABLE Sponsors
	DROP TABLE Fans
	DROP TABLE Coaches
	DROP TABLE Announcers
	
GO

CREATE TABLE Doctors
(
	DOCTOR_ID INT PRIMARY KEY,
	DOCTOR_NAME VARCHAR(50),
	DOCTOR_SALARY int	
);

CREATE TABLE Coaches
(
	COACH_ID INT PRIMARY KEY,
	COACH_NAME VARCHAR(50),
	COACH_SALARY INT	
);

CREATE TABLE Sponsors
(
	SPONSOR_ID INT PRIMARY KEY,
	SPONSOR_NAME VARCHAR(50),
	SPONSOR_NETWORTH INT	
);

CREATE TABLE Fans
(
	FAN_ID INT PRIMARY KEY,
	FAN_NAME VARCHAR(50)
);

CREATE TABLE Fighters
(
	FIGHTER_ID INT PRIMARY KEY,
	FIGHTER_NAME VARCHAR(50),
	FIGHTER_SALARY INT,
	FIGHTER_WEIGHT INT,
	COACH_ID INT,
	FOREIGN KEY (COACH_ID) REFERENCES Coaches(COACH_ID),
);

CREATE TABLE Announcers
(
	ANNOUNCER_ID INT PRIMARY KEY,
	ANNOUNCER_NAME VARCHAR(50),
	ANNOUNCER_SALARY INT	
);

CREATE TABLE Companies
(
	COMPANY_ID INT PRIMARY KEY,
	COMPANY_NAME VARCHAR(50),
	ANNOUNCER_ID INT,
	FOREIGN key(ANNOUNCER_ID) REFERENCES Announcers(ANNOUNCER_ID),
);

CREATE TABLE  Works_for
(
	FIGHTER_ID INT,
	COMPANY_ID INT,
	FOREIGN KEY(FIGHTER_ID) REFERENCES Fighters(FIGHTER_ID),
	FOREIGN key(COMPANY_ID) REFERENCES Companies(COMPANY_ID),
	Constraint WORKS_FOR_ID Primary KEY(FIGHTER_ID,COMPANY_ID)
);

CREATE TABLE Treats
(
	DOCTOR_ID INT,
	FIGHTER_ID INT,
    FOREIGN KEY (DOCTOR_ID) REFERENCES Doctors(DOCTOR_ID),
    FOREIGN KEY(FIGHTER_ID) REFERENCES Fighters(FIGHTER_ID),
	CONSTRAINT Treats_ID Primary KEY(DOCTOR_ID,FIGHTER_ID)
);

CREATE TABLE Supports
(
	SPONSOR_ID INT,
	FIGHTER_ID INT,
	FAN_ID INT,
    FOREIGN KEY (SPONSOR_ID) REFERENCES Sponsors(SPONSOR_ID),
	FOREIGN KEY (FAN_ID) REFERENCES Fans(FAN_ID),
    FOREIGN KEY(FIGHTER_ID) REFERENCES Fighters(FIGHTER_ID),
	CONSTRAINT SUPPORTS_ID Primary KEY(SPONSOR_ID,FAN_ID,FIGHTER_ID)
);